FROM php:7.4-apache


WORKDIR /var/www/html/ 


COPY ./resource .

RUN chown -R www-data:www-data /var/www/html

RUN chmod 755 /var/www/html
RUN find /var/www/html -type f -exec chmod 644 {} \;
RUN find /var/www/html -type d -exec chmod 755 {} \;


RUN apt-get update && apt-get install 



